version: "3"
services:
  arangodb:
    image: arangodb:latest
    container_name: "arangodb"
    environment:
      - ARANGO_NO_AUTH=1
    volumes:
      - arango:/var/lib/arangodb3
    ports:
        - 8529:8529

volumes:
  arango: