version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGODB_ADMIN_USER=mroot
      - MONGODB_ADMIN_PASS=mroot!
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongo:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

volumes:
  mongo: